export const LISTING_CATEGORY_REQUEST = "LISTING_CATEGORY_REQUEST";
export const LISTING_CATEGORY_SUCCESS = "LISTING_CATEGORY_SUCCESS";
export const LISTING_CATEGORY_FAIL = "LISTING_CATEGORY_FAIL";

export const LISTING_DETAILS_REQUEST = "LISTING_DETAILS_REQUEST";
export const LISTING_DETAILS_SUCCESS = "LISTING_DETAILS_SUCCESS";
export const LISTING_DETAILS_FAIL = "LISTING_DETAILS_FAIL";

export const LISTING_OFFER_REQUEST = "LISTING_OFFER_REQUEST";
export const LISTING_OFFER_SUCCESS = "LISTING_OFFER_SUCCESS";
export const LISTING_OFFER_FAIL = "LISTING_OFFER_FAIL";

export const LISTING_CREATE_REQUEST = "LISTING_CREATE_REQUEST";
export const LISTING_CREATE_SUCCESS = "LISTING_CREATE_SUCCESS";
export const LISTING_CREATE_FAIL = "LISTING_CREATE_FAIL";

export const LISTING_USER_REQUEST = "LISTING_USER_REQUEST";
export const LISTING_USER_SUCCESS = "LISTING_USER_SUCCESS";
export const LISTING_USER_FAIL = "LISTING_USER_FAIL";

export const LISTING_DELETE_REQUEST = "LISTING_DELETE_REQUEST";
export const LISTING_DELETE_SUCCESS = "LISTING_DELETE_SUCCESS";
export const LISTING_DELETE_FAIL = "LISTING_DELETE_FAIL";

export const LISTING_EXPLORE_REQUEST = "LISTING_EXPLORE_REQUEST";
export const LISTING_EXPLORE_SUCCESS = "LISTING_EXPLORE_SUCCESS";
export const LISTING_EXPLORE_FAIL = "LISTING_EXPLORE_FAIL";
